-- Time: 28.651
-- Credit: permafrost1812
-- Video: http://youtube.com/watch?v=D3Rw3H-y9PU

MOVIE_CONFIG = {
    fps = 60, -- same as setting frame
}

env.fps=240

movie.playback_speed(1)
movie.start_capture()

print("movie capture started")
movie.frame_advance()
print("test")
movie.frame_advance(50)

print("test")
movie.frame_advance()
key.hold("Escape")
movie.frame_advance()
key.release("Escape")
print("test for skip")

movie.frame_advance()
key.hold("Escape")
movie.frame_advance()
key.release("Escape")
print("test for skip")

movie.frame_advance(40)

print("test end")

movie.frame_advance(10)


print("mouse test")
movie.frame_advance(4)

mouse.move(500,600)
movie.frame_advance(3)


movie.frame_advance()
mouse.move(500,600)
mouse.left(true)
movie.frame_advance()
mouse.move(500,600)
mouse.left(false)

movie.frame_advance()
mouse.move(500,600)
mouse.left(true)
movie.frame_advance()
mouse.move(500,600)
mouse.left(false)

print("end mouse test")
movie.frame_advance(10)


print("should have entered level selection")
movie.frame_advance(120)
print("making sure to be in main menu")

movie.frame_advance(100)
mouse.move(300,850)
print("dificulty")
movie.frame_advance()
mouse.left(true)
movie.frame_advance()
mouse.left(false)

movie.frame_advance(100)
mouse.move(837,600)
print("layer")
movie.frame_advance()
mouse.left(true)
movie.frame_advance()
mouse.left(false)

movie.frame_advance(100)
mouse.move(1600,648)
print("level^")
movie.frame_advance()
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(2)

mouse.move(959,540)
movie.frame_advance(60)
print("done")
movie.frame_advance(60)
print("start movement")
key.hold("tab")
movie.frame_advance()
key.release("tab")
movie.frame_advance()
key.hold("tab")
movie.frame_advance()
key.release("tab")
movie.frame_advance(60)
print("offical------------------------------------------------------------------------------")

movie.frame_advance(200)

print("move to setup")
key.hold("w")
movie.frame_advance(100)
key.hold("2")
movie.frame_advance()
key.release("2")
movie.frame_advance(197)
key.release("w")
mouse.move(960,450)
movie.frame_advance()
key.hold("5")
movie.frame_advance()
key.release("5")
movie.frame_advance(250)
print("rocket one")





mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(6)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(50)
mouse.move(960,551)
movie.frame_advance(50)
print("rocket two")
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(100)
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(30)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(30)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(100)
key.hold("w")
movie.frame_advance(10)
key.release("w")
key.hold("left ctrl")
mouse.move(1677,700)
key.hold("2")
movie.frame_advance()
key.release("2")
mouse.left(true)
movie.frame_advance(160)
mouse.left(false)
movie.frame_advance()
key.hold("5")
movie.frame_advance()
key.release("5")
movie.frame_advance(70)
mouse.move(1677,330)




movie.frame_advance(115)
key.release("left ctrl")
movie.frame_advance()
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(100)

key.hold("5")
movie.frame_advance(100)
key.release("5")
movie.frame_advance(100)



movie.frame_advance(66)
mouse.right(true)

movie.frame_advance(41)
key.hold("left shift")
movie.frame_advance(30)

movie.frame_advance()

print("tunnle done moving on to the blue skull")
movie.frame_advance()
mouse.move(980,600)
mouse.right(false)
key.hold("5")
movie.frame_advance()
key.release("5")
movie.frame_advance()


print("dashing out of tunnel(using these as refrence points")

movie.frame_advance(20)
key.hold("left ctrl")

movie.frame_advance(30)
mouse.move(810,630)
print("moving mouse to shoot rocket")
movie.frame_advance(38)
mouse.left(true)
movie.frame_advance(26)
mouse.left(false)
print("feezing rocket")


mouse.right(true)
movie.frame_advance(2)
mouse.right(false)
movie.frame_advance()
key.hold("2")
movie.frame_advance()
key.release("2")
movie.frame_advance(20)
mouse.left(true)
movie.frame_advance(15)
key.release("left ctrl")
mouse.move(1460,540)

movie.frame_advance(2)
key.hold("r")
key.hold("a")
key.hold("w")
print("grabing skull")
movie.frame_advance()
mouse.move(1677,530)

movie.frame_advance()
mouse.right(true)

print("here")
movie.frame_advance()
mouse.left(false)

movie.frame_advance(7)
key.release("w")
movie.frame_advance(11)
print("ubing")
key.release("a")
movie.frame_advance(90)
key.hold("5")
key.release("r")
print("here2")
mouse.right(false)
movie.frame_advance()
key.release("5")
mouse.move(1677,550)
movie.frame_advance()
key.hold("5")

print("hh")
movie.frame_advance()
key.release("5")
movie.frame_advance(109)
mouse.right(true)

print("after bounce")
movie.frame_advance(4)

movie.frame_advance(65)
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
key.hold("w")
key.hold("a")

movie.frame_advance(5)
key.release("w")
mouse.right(false)
movie.frame_advance(290)
key.release("a")
key.hold("2")
movie.frame_advance(15)
key.release("2")
mouse.right(false)

print("bleh")
movie.frame_advance(126)

key.release("left shift")
movie.frame_advance()
key.hold("left shift")
movie.frame_advance()
key.release("left shift")

movie.frame_advance()
mouse.move(1240,550)
movie.frame_advance(18)
key.hold("left ctrl")
key.hold("w")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(2)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(2)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(2)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(2)
key.hold("left ctrl")
movie.frame_advance(3)
key.release("left ctrl")
movie.frame_advance(5)
print("clip")
mouse.move(1680,550)

key.release("w")
movie.frame_advance(10)
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(80)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
key.hold("4")
movie.frame_advance()
key.release("4")
movie.frame_advance()
print("ub")
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(198)
key.hold("escape")
movie.frame_advance()
key.release("escape")
movie.frame_advance(30)

mouse.move(950,600)
movie.frame_advance()
movie.frame_advance()
mouse.move(950,600)
movie.frame_advance()
movie.frame_advance()
movie.frame_advance()
mouse.left(true)
print("checkpoint")
movie.frame_advance()
mouse.left(false)
movie.frame_advance()
key.hold("left ctrl")
key.hold("1")
movie.frame_advance()
key.release("1")
key.release("left ctrl")
movie.frame_advance()
key.hold("space")
movie.frame_advance()
key.release("space")
mouse.move(950,0)
movie.frame_advance(130)
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(30)
key.hold("space")
movie.frame_advance()
key.release("space")
movie.frame_advance()
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(70)
key.hold("f")
print("punch")
movie.frame_advance()
key.release("f")
movie.frame_advance()
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(30)
key.hold("space")
movie.frame_advance()
key.release("space")
movie.frame_advance()

movie.frame_advance()

movie.frame_advance(70)
key.hold("f")
print("punch")
movie.frame_advance()
key.release("f")
movie.frame_advance()
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(30)
key.hold("space")
movie.frame_advance()
key.release("space")
movie.frame_advance()

movie.frame_advance()

movie.frame_advance(70)
key.hold("f")
print("punch")
movie.frame_advance()
key.release("f")
movie.frame_advance()
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(30)
print("deadcoin one")
mouse.move(950,2000)
movie.frame_advance(30)
mouse.move(950,1500)
movie.frame_advance(30)
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(15)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(250)
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(15)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(10)
key.hold("2")
movie.frame_advance(10)
key.release("2")
movie.frame_advance(10)
key.hold("2")
movie.frame_advance(10)
key.release("2")
movie.frame_advance(10)
key.hold("2")
movie.frame_advance(10)
key.release("2")
print("switch to pump")
movie.frame_advance(10)
movie.frame_advance(10)
mouse.right(true)
movie.frame_advance(10)
movie.frame_advance(10)
movie.frame_advance(50)
key.hold("r")
movie.frame_advance(10)
key.release("r")
print("whip 1")
movie.frame_advance(100)

movie.frame_advance(10)


key.hold("r")
movie.frame_advance(10)
key.release("r")
print("whip 2")
movie.frame_advance(100)

movie.frame_advance(60)
key.hold("space")
movie.frame_advance()
key.release("space")
movie.frame_advance(20)
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(20)
key.hold("space")
movie.frame_advance()
key.release("space")
movie.frame_advance(68)
key.hold("escape")
movie.frame_advance()
key.release("escape")
movie.frame_advance()
key.hold("f")
print("punch 1")

movie.frame_advance()
key.release("f")
mouse.right(false)
movie.frame_advance(10)
mouse.move(950,200)
movie.frame_advance()
key.hold("left shift")
movie.frame_advance()
key.release("left shift")
movie.frame_advance(30)
--key.hold("left ctrl")

movie.frame_advance(20)
--key.release("left ctrl")
mouse.move(900,400)
movie.frame_advance()
mouse.move(1677,560)
--key.hold("space")
movie.frame_advance()
--key.release("space")

movie.frame_advance(38)

key.hold("f")
movie.frame_advance()
key.release("f")
print("punch 2")
movie.frame_advance(20)
mouse.left(true)
print("checking 1 start hold jack")
movie.frame_advance(80)
mouse.move(1040,750)
key.hold("w")
movie.frame_advance(10)
key.hold("left shift")
movie.frame_advance()
key.release("left shift")
movie.frame_advance(70)
key.release("w")
movie.frame_advance()

movie.frame_advance(30)
key.hold("f")
movie.frame_advance()
key.release("f")
print("punch 3")
movie.frame_advance(10)


mouse.move(1040,480)
movie.frame_advance()
key.hold("left shift")
movie.frame_advance()
key.release("left shift")

print("dash 1")

movie.frame_advance(20)
mouse.move(900,500)


movie.frame_advance(20)
print("dash 2")

key.hold("left shift")
movie.frame_advance()
mouse.move(960,500)
key.release("left shift")
movie.frame_advance()
key.hold("space")
movie.frame_advance()

key.release("space")

movie.frame_advance(27)
mouse.left(false)

print("hit with jackhammer")
movie.frame_advance(9)
mouse.move(1677,540)
movie.frame_advance()
mouse.move(940,810)

movie.frame_advance(25)

movie.frame_advance(17)
key.hold("f")
print("hit!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
movie.frame_advance()
key.release("f")
movie.frame_advance(50)

print("guh")


movie.frame_advance()

movie.frame_advance(450)
key.hold("left shift")

movie.frame_advance()
key.release("left shift")
print("hi fishy")
print("hi pumpkin")

movie.frame_advance(300)
key.hold("escape")

movie.frame_advance()
key.release("escape")

movie.frame_advance(30)
key.hold("escape")

movie.frame_advance()
key.release("escape")

movie.frame_advance()
mouse.move(1677,540)
key.hold("5")
movie.frame_advance()
mouse.move(985,205)
key.release("5")
movie.frame_advance(145)
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance()
key.hold("2")
mouse.move(950,900)
print("time for safe strat")
movie.frame_advance()
key.release("2")
movie.frame_advance()
mouse.right(true)
movie.frame_advance(20)
mouse.left(true)
movie.frame_advance(135)
mouse.right(false)
mouse.left(false)
movie.playback_speed(1)
movie.frame_advance(55)
mouse.move(1677,540)
movie.frame_advance()

mouse.move(938,547)
movie.frame_advance(5)
key.hold("r")
key.hold("1")
movie.frame_advance(120)
key.release("1")
movie.playback_speed(1)
key.hold("o")
movie.frame_advance()
key.release("o")
movie.frame_advance()
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance()
key.hold("o")
movie.frame_advance()
key.release("o")
movie.frame_advance()
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance()
key.hold("o")
movie.frame_advance()
key.release("o")
movie.frame_advance()
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(20)
mouse.move(1003,460)
movie.frame_advance(165)
key.hold("4")
movie.frame_advance()
key.release("4")
movie.frame_advance(87)
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance()
key.hold("1")
movie.frame_advance()
key.release("1")
movie.frame_advance()
key.hold("1")
movie.frame_advance()
key.release("1")
movie.frame_advance()
mouse.right(true)
movie.frame_advance()
movie.frame_advance()
movie.frame_advance()
movie.frame_advance()
movie.frame_advance()

movie.frame_advance()
movie.frame_advance()
key.release("r")

key.hold("f")


movie.frame_advance()


key.release("f")
movie.frame_advance()

print("hookpoint cancel")
mouse.move(922,753)
movie.frame_advance()

movie.frame_advance(295)
mouse.right(false)
movie.playback_speed(1)
movie.frame_advance()
key.hold("5")
movie.frame_advance()
key.release("5")
movie.frame_advance(105)
mouse.move(1003,1)
movie.frame_advance(211)
key.hold("left ctrl")
movie.frame_advance()
key.release("left ctrl")
movie.frame_advance(30)
key.hold("s")
movie.frame_advance()
key.hold("left ctrl")
movie.frame_advance(39)
key.release("left ctrl")
movie.frame_advance()
key.hold("left ctrl")
movie.frame_advance()

key.release("s")
key.release("left ctrl")
movie.frame_advance()
mouse.move(903,830)
movie.frame_advance(35)
key.hold("left shift")
movie.frame_advance()
key.release("left shift")
movie.frame_advance()
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance(9)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance()
movie.frame_advance(15)
movie.playback_speed(1)
mouse.right(true)
movie.frame_advance(20)
mouse.right(false)
key.hold("s")

movie.frame_advance(10)

movie.frame_advance(28)
key.release("s")
movie.frame_advance(22)
key.hold("d")
movie.frame_advance(8)
key.release("d")
movie.frame_advance(70)

print("hi sillyplilly")
movie.frame_advance()